name: Ruby Gem

# on:
#   release:
#     types: created

on:
  push:
    branches:
      - publish-with-action

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install dependencies
      run: bundle install
    - name: Publish to RubyGems
      run: |
        bundle exec rake install
        bundle exec rake release
      env:
        GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}
